### ISSUE TITLE
Design the UX and UI wireframe for non-gameplay

### ISSUE THREAD

**Issue by caoxantb** [caoxantb/g21-adhd-kinesthetic-game#49]

**Comment by risha-parveen** [comment]
Non-gameplay prototype version 1

[](https://www.figma.com/proto/thdUNYbONfBGapIDZ0f2Yd/G21-adhd-game?node-id=18-6&node-type=canvas&t=jg5iyLEiWtPDj8Rs-1&scaling=scale-down&content-scaling=fixed&page-id=0%3A1)

@caoxantb @wuannan  please review

**Comment by caoxantb** [comment]
@risha-parveen Looks neat! Could you share also the working panel of figma prototype, not just the prototype itself.
